# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damndaily',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
