# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170824_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='today',
            name='at',
        ),
        migrations.AddField(
            model_name='today',
            name='day',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='today',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
