# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170824_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='today',
            old_name='damn_daily',
            new_name='damndaily',
        ),
    ]
