# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_message_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=64)),
                ('individual', models.CharField(max_length=64)),
                ('gender', models.SmallIntegerField()),
            ],
        ),
    ]
